apiVersion: v1
kind: Secret
metadata:
  name: {{ include "somekube.fullname" . }}-environment
stringData:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value }}
  {{- end }}
  MONGODB_CONNECTION_URI: mongodb://{{ index .Values.mongodb.auth.usernames 0 }}:{{ index .Values.mongodb.auth.passwords 0 }}@{{ include "mongodb.service.nameOverride" .Subcharts.mongodb }}/{{ index .Values.mongodb.auth.databases 0 }}
